# Generated by Django 5.2.1 on 2025-07-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_timestamp_alter_attendance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='timestamp',
        ),
    ]
